### ISSUE TITLE
无法生成appid.txt

### ISSUE THREAD

**Issue by Lyris01** [thunlp/ProactiveAgent#1]
运行main.py报错
  File "/mnt/d/workspace/ProactiveAgent/agent/main.py", line 52, in root
    return {'appid': appid}
NameError: name 'appid' is not defined

**Comment by SummerFall1819** [comment]
我们留意到你使用的平台是 Linux 平台。

我们目前的 demo 只支持 Windows 平台，因为其具备 Toast 提醒用户的接口。而 `appid` 专门用于为我们的程序注册一个 ID 以实现 Toast 交互功能。

Linux 平台暂时没有适配类似的通知功能，我们会在之后提供对应的[相关支持](https://wiki.archlinux.org/title/Desktop_notifications)
