### ISSUE TITLE
The command for running ragent.py is not correct

### ISSUE THREAD

**Issue by Ch1ldKing** [thunlp/ProactiveAgent#10]
## What have I done?
- I created a conda env, and installed all the requirements.
- I installed all the plugins and the server of ActivityWatch. 
![image](https://github.com/user-attachments/assets/f490ba81-9d06-4baf-bf14-0c25c4a02a5e)
- The agent/main.py is running correctly.
![image](https://github.com/user-attachments/assets/02324d07-aa0b-4e0d-800b-f733efca58d7)
## What problem I met?
- I want to run the agent/ragent.py follow the tutorial in the agent/README.md `python ragent.py --apps chrome.exe' , but It doesn't work.
![image](https://github.com/user-attachments/assets/3d23c40e-829e-4be6-9d24-05895510296f)
## What did I try?
I found that in the agent/ragent.py, there is a newer command `python ragent.py --platform PC --chromes explorer.exe,mesdge.exe` ,for that arguments in the new version has one called **platform**.

I want to know how to run it correctly?

**Comment by SummerFall1819** [comment]
You should use the command in the `agent/ragent.py` to run the demo.  The `readme.md` file was created when we only support PC and didn't make the update in-time. Thank you for pointing that out. We'll update the doc immediately to erase this confusion.
