### ISSUE TITLE
the file requirements_mac.txt  not in ./agent

### ISSUE THREAD

**Issue by yupaiLy** [thunlp/ProactiveAgent#12]
Hi, I can not find the file `requirements_mac.txt` in `./agent`, please help me.

**Comment by SummerFall1819** [comment]
We merged the `requirements_mac.txt` and `requirements.txt` with `requirements.txt` under root folder. We'll update the relative document for that confusion (That is, the dependency download process could be skipped as long as you already installed the requirements under root folder).
Also, we didn't fully test the performance under MacOS, and we're preparing the support for MacOS as described in issue #8. You may occur bugs during running the scripts. So it is currently advised to run our demo in windows.

我们将 `requirements_mac.txt` 和 `requirements.txt` 与项目根目录下的 `requirements.txt` 进行了合并，我们会为其误解更新对应部分的文档。
我们并没有完全测试过在 MacOS 下的表现，并且我们正在准备对 MacOS 的支持，在运行脚本时您可能会遭遇错误，现在更推荐在 windows 下体验我们的 demo.

**Comment by yupaiLy** [comment]
thanks, but  the docs `./gym/example_config.toml` seems to have the same problem?

**Comment by SummerFall1819** [comment]
> thanks, but the docs `./gym/example_config.toml` seems to have the same problem?

Yes. We use separate configuration files during the experiment, and we merged the two without updating the doc. We are sorry for the confusions made. There's only one configuration file under root folder is enough.
是的，我们在运行实验时用了不同的两个配置文件，我们在没有更新文档的情况下合并了两个文件，我们为造成的困惑深感抱歉。一份在根目录下的配置文件就已经足够了。

**Comment by yupaiLy** [comment]
When I execute `python ragent.py --platform PC --chromes Code.exe, chrome.exe, explorer.exe --interval 10`, the following error 404 will be reported.
![微信图片_20241206172421](https://github.com/user-attachments/assets/f8db032a-9f60-4ec8-ae2e-e4e2ac5693ce)

**Comment by SummerFall1819** [comment]
> When I execute `python ragent.py --platform PC --chromes Code.exe, chrome.exe, explorer.exe --interval 10`, the following key error will be reported. ![微信图片_20241206172421](https://private-user-images.githubusercontent.com/93436468/393183867-f8db032a-9f60-4ec8-ae2e-e4e2ac5693ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Nzc3MTEsIm5iZiI6MTczMzQ3NzQxMSwicGF0aCI6Ii85MzQzNjQ2OC8zOTMxODM4NjctZjhkYjAzMmEtOWY2MC00ZWM4LWFlMmUtZTRlMmFjNTY5M2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MzAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YzhmYTI2NTYzNDAyZmNiYWE1ZjQxN2FhYjE3ZTNiOWFhM2I5MGJhMTE5ODU0NDM0NWIwY2ZmODg0MTZkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y8hfMRoSj5jCvBqxvkx9kpRc55_aUT_b6nT5ofVX1Ss)

Try changing the `default_completion_model` from `gpt-4o` to `activeagent` since you didn't provide the api-key for `gpt-4o`. We'll dive into the configuration settings and fix that issue for default parameter actions.
尝试将 `default_completion_model` 从 `gpt-4o` 更换为 `activeagent`，因为您并没有提供 `gpt-4o` 的相关配置信息，我们会深入检查配置设置并且基于默认参数行为修复这个问题。

**Comment by yupaiLy** [comment]
Thanks! I succeeded
