### ISSUE TITLE
APIConfig' object has no attribute 'base_url'

### ISSUE THREAD

**Issue by NekoMirra** [thunlp/ProactiveAgent#2]
![PixPin_2024-12-02_22-04-06](https://github.com/user-attachments/assets/d158ce26-2ba5-4930-8ebe-2b5053f135bd)

**Comment by AiHaI-Ai** [comment]
apiconfig object with Keyerror 'activeagent'
![image](https://github.com/user-attachments/assets/e3cd0de4-912f-485d-8887-902ac071478a)
