### ISSUE TITLE
什么时候计划提供agent_data?

### ISSUE THREAD

**Issue by EmeryBAI** [thunlp/ProactiveAgent#20]
您好，我看到这项工作认为很有开创性。想要复现你们的工作，请问你们的agent_data 计划什么时候release。 谢谢！

**Comment by SummerFall1819** [comment]
Hello, we upload our data via google drive and update the link in `./dataset/agent_data/README.md`, would you mind checking if the link works?

你好，我们通过谷歌云盘上传了我们的数据，并且更新了 `./dataset/agent_data/README.md` 的链接，你能协助检查链接是否有效吗？

**Comment by EmeryBAI** [comment]
That is valid, thx. Btw, may I ask whether you plan to release the reward model weight?

谢谢，链接是有效的。顺便我想询问你们是否有计划发布reward 模型的参数。

**Comment by SummerFall1819** [comment]
Well yes, we plan to release our reward model weight on the hugging face in the near future, once we released we will update the doc ASAP.

是的，我们计划在近期于 hugging face 上公开我们的 reward model 参数，发布之后我们会立刻更新文档。

**Comment by EmeryBAI** [comment]
Thank you for your reply. Finally, I would like to ask about the fine-tuning strategy. Do u use full parameter tuning or some other strategies such as LoRA? Is LLAMA_factory used as the framework? If possible, I hope to try to make the relevant code public. Thank you again. :)

很感谢你的回复。我最后还想询问关于微调上的策略， 我们是采用了全参微调吗还是一些别的策略如LoRA。在框架上是采用了LLAMA_factory 是吗？如果可以的话相关的代码希望可以试着公开，再次感谢。

**Comment by SummerFall1819** [comment]
We used full parameter tuning and LLaMA_factory as the framework. The detail of the training process can be found in our article. As for the code, you should refer to the document and code of LLaMA factory as we didn't apply any strategies that need to point out specially.
我们采用了全参微调，使用 LLaMA_factory 作为框架，训练流程的细节可以从我们的文章中找到。至于相关的代码你应该参考 LLaMA_factory 上的文档和代码，我们并没有采用什么值得特别指出的策略。
