### ISSUE TITLE
task_status的含义？

### ISSUE THREAD

**Issue by fanbooo** [thunlp/ProactiveAgent#6]
感谢作者的工作；
看完论文和代码我有一个疑惑，./datasets/test_data/*.json 中的每段数据，"task_status": true/"task_status": false 这个是什么意思？
我理解的是：这个是真实用户选择是否执行candidate_task中的任务，属于是真实人的行为；对应到trian data pipeline里应该是userAgent生成的？

**Comment by luyaxi** [comment]
> 这个是真实用户选择是否执行candidate_task中的任务，属于是真实人的行为；

该字段在设计之初的用处确实如此。但在后期迭代中，该字段已经事实上被废弃。

> 对应到trian data pipeline里应该是userAgent生成的？

是的，按照论文里所说的，我们将（基于Reward Model）userAgent 的判别任务分成了4类，并在判定模型提出的任务时完全交由Reward Model进行评价。
