### ISSUE TITLE
Apiconfig with Keyerror 'activeagent'

### ISSUE THREAD

**Issue by AiHaI-Ai** [thunlp/ProactiveAgent#7]
![image](https://github.com/user-attachments/assets/66729ff3-cdbf-4524-b6bc-9004d4c5ed96)

**Comment by SummerFall1819** [comment]
Please follow the guide in `example_config.toml` and fill the fields in `activeagent` as new `config.toml`.

请根据 `example_config.toml` 的指引填写 `activeagent` 字段作为新的 `config.toml`.
