### ISSUE TITLE
ImportError: cannot import name 'EventListener' from 'agentmodule' 

### ISSUE THREAD

**Issue by shouldnotappearcalm** [thunlp/ProactiveAgent#8]
运行 ActiveAgent#main 报错下面的不存在

from agentmodule import (EventListener, ContextManager, Trigger, Core, LLMClient)

```log
ImportError: cannot import name 'EventListener' from 'agentmodule' 
```

**Comment by luyaxi** [comment]
请检查执行路径中是否包含`agentmodule.py`文件。

**Comment by SummerFall1819** [comment]
If you want to let the agent propose task based on the events, try running `./eval/scripts.py` instead.  All the modules mentioned in ImportError are from an older version which are deprecated.
如果您希望让智能体根据事件预测任务，请尝试运行 `./eval/scripts.py` 作为替代。报错的这些组件来自于更早的版本，已经被废弃。

If you want to run the demo, try running `./eval/ragent.py` instead. 
如果您希望运行 demo，尝试运行 `./eval/ragent.py` 作为替代。

**Comment by shouldnotappearcalm** [comment]
@SummerFall1819 eval下面好像没有 ragent.py

**Comment by SummerFall1819** [comment]
> @SummerFall1819 eval下面好像没有 ragent.py

Sorry for confusion, we update the original comment.
抱歉打错了，我们更新了原本的回复

**Comment by shouldnotappearcalm** [comment]
要是能支持下 MacOS 就好了

**Comment by SummerFall1819** [comment]
> 要是能支持下 MacOS 就好了

We understand your concerns and did some initial works on support for MacOS. We planned to use [macOS notifications](https://github.com/Jorricks/macos-notifications) as our first approach.  Unfortunately the related documents were not accessible during our development so we had to pause the support. We are aware that the project could be reached again, and we will continue our development. Thanks for you advice.

非常理解，事实上我们已经有了一些前期的工作。我们原本打算使用 [macOS notifications](https://github.com/Jorricks/macos-notifications) 。但是在开发过程中相关文档关闭导致我们不得不停止 MacOS的相应开发，最近项目重新开放了，我们将会继续我们的开发。感谢您的建议。

**Comment by shouldnotappearcalm** [comment]
期待，很好的研究
