### ISSUE TITLE
demo video is not available

### ISSUE THREAD

**Issue by Raysquare** [thunlp/ProactiveAgent#9]
the demo video on readme is not available. 
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/6485beb0-3f20-4a18-a311-034f69345265">

**Comment by luyaxi** [comment]
The video is on GitHub attachment https://github.com/user-attachments/assets/4a9152e8-15ee-4bdf-a917-52a9e6b4f375. 
 Please check your internet connection or wait for a few seconds, as we could not replicate the error. If you still can not load the video, try to switch your network.

**Comment by edsml-js222** [comment]
Hi! I can't load the demo video either, and also the video link above seems to be 404🤔
![屏幕截图 2024-12-07 094136](https://github.com/user-attachments/assets/6fa15677-c997-4da4-a00e-c573df33ba15)
![屏幕截图 2024-12-07 094216](https://github.com/user-attachments/assets/64a346cf-7b9d-4112-afb4-0ea6fd42914a)

**Comment by SummerFall1819** [comment]
> Hi! I can't load the demo video either, and also the video link above seems to be 404🤔 ![屏幕截图 2024-12-07 094136](https://private-user-images.githubusercontent.com/110098381/393461981-6fa15677-c997-4da4-a00e-c573df33ba15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDAzMTksIm5iZiI6MTczMzU0MDAxOSwicGF0aCI6Ii8xMTAwOTgzODEvMzkzNDYxOTgxLTZmYTE1Njc3LWM5OTctNGRhNC1hMDBlLWM1NzNkZjMzYmExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmZlM2U4Y2I2NDEzYjVhYWEzZWU1MmVkMGQwMmE3ZTkyNTJmODA2ZDkwZDU1ZDljZTI3OWM2MzEwNmJlOWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3ipBw5uDgWelhHnA9ZRIZINkmK5hID_LJuJxP-s9X0I) ![屏幕截图 2024-12-07 094216](https://private-user-images.githubusercontent.com/110098381/393461987-64a346cf-7b9d-4112-afb4-0ea6fd42914a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDAzMTksIm5iZiI6MTczMzU0MDAxOSwicGF0aCI6Ii8xMTAwOTgzODEvMzkzNDYxOTg3LTY0YTM0NmNmLTdiOWQtNDExMi1hZmI0LTBlYTZmZDQyOTE0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzlhMjQ5ODg5NDZjNDk3NWMwZDUzNjE1YjhhNmQ1YWRmMTUyNDhkN2I2NzZkMmU3ZjJkNjAzYTkwNDNkNjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WKv2hhcwjiu8_xPoHsXSkIlrlIp95hMYcYX4w5bhABM)

The video is rendered properly and the link works well for me. I suppose this should be a network connection error. What chrome are you using and did you use any proxy?
我这边视频正常渲染，链接也是正常的。我觉得这个应该是网络连接问题。你用的什么浏览器？你有用任何网络代理吗？

**Comment by edsml-js222** [comment]
> > Hi! I can't load the demo video either, and also the video link above seems to be 404🤔 ![屏幕截图 2024-12-07 094136](https://private-user-images.githubusercontent.com/110098381/393461981-6fa15677-c997-4da4-a00e-c573df33ba15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDAzMTksIm5iZiI6MTczMzU0MDAxOSwicGF0aCI6Ii8xMTAwOTgzODEvMzkzNDYxOTgxLTZmYTE1Njc3LWM5OTctNGRhNC1hMDBlLWM1NzNkZjMzYmExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmZlM2U4Y2I2NDEzYjVhYWEzZWU1MmVkMGQwMmE3ZTkyNTJmODA2ZDkwZDU1ZDljZTI3OWM2MzEwNmJlOWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3ipBw5uDgWelhHnA9ZRIZINkmK5hID_LJuJxP-s9X0I) ![屏幕截图 2024-12-07 094216](https://private-user-images.githubusercontent.com/110098381/393461987-64a346cf-7b9d-4112-afb4-0ea6fd42914a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDAzMTksIm5iZiI6MTczMzU0MDAxOSwicGF0aCI6Ii8xMTAwOTgzODEvMzkzNDYxOTg3LTY0YTM0NmNmLTdiOWQtNDExMi1hZmI0LTBlYTZmZDQyOTE0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwMjUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzlhMjQ5ODg5NDZjNDk3NWMwZDUzNjE1YjhhNmQ1YWRmMTUyNDhkN2I2NzZkMmU3ZjJkNjAzYTkwNDNkNjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WKv2hhcwjiu8_xPoHsXSkIlrlIp95hMYcYX4w5bhABM)
> 
> The video is rendered properly and the link works well for me. I suppose this should be a network connection error. What chrome are you using and did you use any proxy? 我这边视频正常渲染，链接也是正常的。我觉得这个应该是网络连接问题。你用的什么浏览器？你有用任何网络代理吗？

That's weird🤔, I do use vpn since I am in Shenzhen. For brower, I tired Microsoft Edge and Chrome, both failed. May I know what brower are you using?
很怪，我windows自带的的那个edge和chrome这两个浏览器试了都不行，我在国内挂着vpn，不知道是不是这个的原因。但是让一个澳洲的朋友看了一眼也是没有正常渲染视频，能问问你用的浏览器是什么吗

**Comment by Thespica** [comment]
video not available +1, maybe changing source can bring better demonstration.

![image](https://github.com/user-attachments/assets/e630e5ec-a982-44b5-86e3-e7767621b381)
![image](https://github.com/user-attachments/assets/09f83ae6-0b51-4fa7-ae85-9c3e62e25086)

**Comment by SummerFall1819** [comment]
@Raysquare @edsml-js222 @Thespica We apologize for the video issue. It turned out that the source for the demo is from another private repo from us, that's why we can't reproduce the problem when we are logged in. We update the video source and please check if the demo video rendered correctly.

**Comment by edsml-js222** [comment]
I think the video works now, thanks!😀
